import React from 'react';
import './style.css';
import { Box } from '@mui/system';
import Navbar from "../Navbar/NavbarComponent";
import MobileNavbar from "../MobileNavbar/MobileNavbarComponent";

const PrivacyPolicy = () => {
    return (
        <div>
            <Box>
                <Navbar />
            </Box>
            <Box>
                <MobileNavbar />
            </Box>

            <Box className="privacy-policy-content">
                <Box className="privacy-policy-text">
                    <div className="doc-title">PRIVACY POLICY</div>
                    <div className="doc-date">Effective date: 09/23/2021</div>
                    <div className="doc-section-title">
                        1. Introduction
                    </div>
                    <div className="doc-section-content">
                        Welcome to Tech Telos Inc <br/><br/>
                        Tech  Telos  Inc (“us”,  “we”,  or  “our”)  operates swingscalp.com  and  SwingScalp  mobile application (hereinafter referred to as “<b>Service</b>”).<br/><br/>
                        Our Privacy Policy governs your visit to swingscalp.com and SwingScalp mobile application, and explains how we collect, safeguard and disclose information that results from your use of our Service.<br/><br/>
                        We  use  your  data  to  provide  and  improve  Service.  By  using  Service,  you  agree  to  the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.<br/><br/>
                        Our  Terms  and  Conditions  (“<b>Terms</b>”)  govern  all  use  of  our  Service  and  together  with  the Privacy Policy constitutes your agreement with us (“<b>agreement</b>”).<br/>
                    </div>
                    <div className="doc-section-title">
                        2. Definitions
                    </div>
                    <div className="doc-section-content">
                        <b>SERVICE</b> means the swingscalp.com website and SwingScalp mobile application operated by Tech Telos Inc<br/><br/>
                        <b>PERSONAL DATA</b> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).<br/><br/>
                        <b>USAGE DATA</b> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).<br/><br/>
                        <b>COOKIES</b> are small files stored on your device (computer or mobile device).<br/><br/>
                        <b>DATA CONTROLLER</b> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.<br/><br/>
                        <b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.<br/><br/>
                        <b>DATA SUBJECT</b> is any living individual who is the subject of Personal Data.<br/><br/>
                        <b>THE USER</b> is the individual using ods to the Data Subject, who is the subject of Personal Data."
                    </div>

                    <div className="doc-section-title">
                        3. Information Collection and Use
                    </div>
                    <div className="doc-section-content">
                        We collect several different types of information for various purposes to provide and improve our Service to you.
                    </div>
                    
                    <div className="doc-section-title">
                        4. Types of Data Collected
                    </div>
                    <div className="doc-section-content">
                        <b>Personal Data</b><br/>
                        While using our Service, we may ask you to provide us with certain personally identifiable information  that  can  be  used  to  contact  or  identify  you  (“<b>Personal  Data</b>”).  Personally identifiable information may include, but is not limited to:<br/><br/>
                        (a) Email address<br/><br/>
                        (b) First name and last name<br/><br/>
                        (c)  Phone number<br/><br/>
                        (d) Address, State, Province, ZIP/Postal code, City<br/><br/>
                        (e) Cookies and Usage Data<br/><br/>
                        We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at support@swingscalp.com.<br/><br/>
                        <b>Usage Data</b><br/>
                        We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (“<b>Usage Data</b>”).<br/><br/>
                        This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.<br/><br/>
                        When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.<br/><br/>
                        <b>Location Data</b><br/>
                        We may use and store information about your location if you give us permission to do so (“<b>Location  Data</b>”).  We  use  this  data  to  provide  features  of  our  Service,  to  improve  and customize our Service.<br/><br/>
                        You can enable or disable location services when you use our Service at any time by way of your device settings.<br/><br/>

                        <b>Tracking Cookies Data</b><br/>
                        We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.<br/><br/>
                        Cookies  are  files  with  a  small  amount  of  data  which  may  include  an  anonymous  unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.<br/><br/>
                        You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.<br/><br/>
                        Examples of Cookies we use:<br/><br/>
                        (a) <b>Session Cookies:</b> We use Session Cookies to operate our Service.<br/><br/>
                        (b) <b>Preference Cookies:</b> We use Preference Cookies to remember your preferences and various settings.<br/><br/>
                        (c) <b>Security Cookies:</b> We use Security Cookies for security purposes.<br/><br/>
                        (d) <b>Advertising Cookies:</b> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.<br/><br/>
                        <b>Other Data</b><br/>
                        While using our Service, we may also collect the following information: sex, age, date of birth, place  of  birth,  passport  details,  citizenship,  registration  at  place  of  residence  and  actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, non-disclosure agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.<br/><br/>
                    </div>
                    <div className="doc-section-title">
                        5. Use of Data
                    </div>
                        Tech Telos Inc uses the collected data for various purposes:<br/><br/>
                        (a) to provide and maintain our Service;<br/><br/>
                        (b) to notify you about changes to our Service;<br/><br/>
                        (c) to allow you to participate in interactive features of our Service when you choose to do so;<br/><br/>
                        (d) to provide customer support;<br/><br/>
                        (e) to gather analysis or valuable information so that we can improve our Service;<br/><br/>
                        (f) to monitor the usage of our Service;<br/><br/>
                        (g) to detect, prevent and address technical issues;<br/><br/>
                        (h) to fulfill any other purpose for which you provide it;<br/><br/>
                        (i) to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;<br/><br/>
                        (j) to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;<br/><br/>
                        (k) to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;<br/><br/>
                        (l) in any other way we may describe when you provide the information;<br/><br/>
                        (m) for any other purpose with your consent.
                    <div className="doc-section-content">
                    </div>
                    <div className="doc-section-title">
                        6. Retention of Data
                    </div>
                    <div className="doc-section-content">
                        We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.<br/><br/>
                        We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                    </div>

                    <div className="doc-section-title">
                        7. Transfer of Data
                    </div>
                    <div className="doc-section-content">
                        Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.<br/><br/>
                        If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.<br/><br/>
                        Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.<br/><br/>
                        Tech Telos Inc will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
                    </div>
                    <div className="doc-section-title">
                        8. Disclosure of Data
                    </div>
                    <div className="doc-section-content">
                        We may disclose personal information that we collect, or you provide:<br/><br/>
                        (a) <b>Disclosure for Law Enforcement.</b><br/>
                        Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.<br/><br/>
                        (b) <b>Business Transaction.</b><br/>
                        If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.<br/><br/>
                        (c) <b>Other cases. We may disclose your information also:</b><br/><br/>
                        (i) to our subsidiaries and affiliates;<br/><br/>
                        (ii) to contractors, service providers, and other third parties we use to support our business;<br/><br/>
                        (iii) to fulfill the purpose for which you provide it;<br/><br/>
                        (iv) for any other purpose disclosed by us when you provide the information;<br/><br/>
                        (v) with your consent in any other cases;<br/><br/>
                        (vi) if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.
                    </div>
                    <div className="doc-section-title">
                        9. Security of Data
                    </div>
                    <div className="doc-section-content">
                        The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                    </div>
                    <div className="doc-section-title">
                        10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)
                    </div>
                    <div className="doc-section-content">
                        If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. – See more at https://eur- lex.europa.eu/eli/reg/2016/679/oj <br/><br/>
                        We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.<br/><br/>
                        If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at support@swingscalp.com.<br/><br/>
                        In certain circumstances, you have the following data protection rights:<br/><br/>
                        (a) the right to access, update or to delete the information we have on you;<br/><br/>
                        (b) the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;<br/><br/>
                        (c) the right to object. You have the right to object to our processing of your Personal Data;<br/><br/>
                        (d) the right of restriction. You have the right to request that we restrict the processing of your personal information;<br/><br/>
                        (e) the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;<br/><br/>
                        (f) the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;<br/><br/>
                        Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.<br/><br/>
                        You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
                    </div>
                    <div className="doc-section-title">
                        11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)
                    </div>
                    <div className="doc-section-content">
                        CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. – See more at: https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy- protection-act-caloppa-3/<br/><br/>
                        According to CalOPPA we agree to the following:<br/><br/>
                        (a) users can visit our site anonymously;<br/><br/>
                        (b) our Privacy Policy link includes the word “Privacy”, and can easily be found on the page specified above on the home page of our website;<br/><br/>
                        (c) users will be notified of any privacy policy changes on our Privacy Policy Page;<br/><br/>
                        (d) users are able to change their personal information by emailing us at support@swingscalp.com.<br/><br/>
                        Our Policy on “Do Not Track” Signals:<br/><br/>
                        We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.<br/><br/>
                        You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser."
                    </div>
                    <div className="doc-section-title">
                        12. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)
                    </div>
                    <div className="doc-section-content">
                        If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:<br/><br/>
                        (a) <b>What personal information we have about you</b>. If you make this request, we will return to you:<br/><br/>
                        (i) The categories of personal information we have collected about you.<br/><br/>
                        (ii) The categories of sources from which we collect your personal information.<br/><br/>
                        (iii) The business or commercial purpose for collecting or selling your personal information.<br/><br/>
                        (iv) The categories of third parties with whom we share personal information.<br/><br/>
                        (v) The specific pieces of personal information we have collected about you.<br/><br/>
                        (vi) A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.<br/><br/>
                        (vii)A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.<br/><br/>
                        Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.<br/><br/>
                        (b) <b>To delete your personal information</b>. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.<br/><br/>
                        (c) <b>To stop selling your personal information</b>. If you submit a request to stop selling your personal information, we will stop selling it. If you are a California resident, to opt-out of the sale of your personal information, click “Do Not Sell My Personal Information” at the bottom of our home page to submit your request.<br/><br/>
                        Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.<br/><br/>
                        To exercise your California data protection rights described above, please send your request(s) by one of the following means:<br/><br/>
                        By email: support@swingscalp.com<br/><br/>
                        By mail: 2401 Fountain View Drive, Suite 224 #2456,Houston, TX 77057<br/><br/>
                        Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.
                    </div>

                    <div className="doc-section-title">
                        13. Service Providers
                    </div>
                    <div className="doc-section-content">
                        We may employ third party companies and individuals to facilitate our Service (“<b>Service Providers</b>”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.<br/><br/>
                        These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                    </div>

                    <div className="doc-section-title">
                        14. Analytics
                    </div>
                    <div className="doc-section-content">
                        We may use third-party Service Providers to monitor and analyze the use of our Service.<br/><br/>
                        <b>Google Analytics</b><br/>
                        Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.<br/><br/>
                        For more information on the privacy practices of Google, please visit the <a href="https://policies.google.com/privacy?hl=en">Google Privacy Terms web page</a><br/><br/>
                        We also encourage you to review the <a href="https://support.google.com/analytics/answer/6004245">Google's policy</a> for safeguarding your data.
                    </div>

                    <div className="doc-section-title">
                        15. CI/CD tools
                    </div>
                    <div className="doc-section-content">
                        We may use third-party Service Providers to automate the development process of our Service.<br/><br/>
                        <b>GitHub</b><br/>
                        GitHub is provided by GitHub, Inc.<br/><br/>
                        GitHub is a development platform to host and review code, manage projects, and build software.<br/><br/>
                        For more information on what data GitHub collects for what purpose and how the protection of the data is ensured, please visit <a href="https://help.github.com/en/articles/github-privacy-statement">GitHub Privacy Policy page</a>.
                    </div>

                    <div className="doc-section-title">
                        16. Advertising
                    </div>
                    <div className="doc-section-content">
                        We may use third-party Service Providers to show advertisements to you to help support and maintain our Service.<br/><br/>
                        <b>Google AdSense DoubleClick Cookie</b><br/>
                        Google, as a third party vendor, uses cookies to serve ads on our Service. Google's use of the DoubleClick cookie enables it and its partners to serve ads to our users based on their visit to our Service or other websites on the Internet.<br/><br/>
                        You may opt out of the use of the DoubleClick Cookie for interest-based advertising by visiting the <a href="http://www.google.com/ads/preferences/">Google Ads Settings web page</a><br/><br/>
                        <b>Bing Ads</b><br/>
                        Bing Ads is an advertising service provided by Microsoft Inc.<br/><br/>
                        You can opt-out from Bing Ads by following the instructions on Bing Ads Opt-out <a href="https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads">page</a><br/><br/>
                        For more information about Bing Ads, please visit their <a href="https://privacy.microsoft.com/en-us/PrivacyStatement">Privacy Policy page</a><br/><br/>
                        <b>AdMob by Google</b><br/>
                        AdMob by Google is provided by Google Inc.
                        You can opt-out from the AdMob by Google service by following the <a href="https://support.google.com/ads/answer/2662922?hl=en">instructions</a> described by Google.<br/><br/>
                        For more information on how Google uses the collected information, please visit the “How Google uses data when you use our partners' sites or app” <a href="http://www.google.com/policies/privacy/partners/">page</a> or visit the <a href="http://www.google.com/policies/privacy/">Privacy Policy of Google</a><br/><br/>
                        <b>AdButler</b><br/>
                        AdButler is an advertising service provided by Sparklit Networks Inc.<br/><br/><br/>
                        For more information about AdButler, please visit their <a href="https://www.sparklit.com/agreements.spark?agreement=privacy">Privacy Policy page</a><br/><br/>
                        <b>Unity Ads</b><br/>
                        Unity Ads is provided by Unity Technologies.<br/><br/>
                        You can opt-out from Unity Ads service by following the instructions as described by Unity Technologies on their <a href="https://unity3d.com/legal/privacy-policy">Privacy Policy page</a><br/><br/>
                        For more information about Unity Technologies, please visit <a href="https://unity3d.com/legal/privacy-policy">Unity Technologies Privacy Policy</a><br/><br/>
                    </div>
                    
                    <div className="doc-section-title">
                        17. Behavioral Remarketing
                    </div>
                    <div className="doc-section-content">
                        Tech Telos Inc uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.<br/><br/>
                        <b>Google Ads (AdWords)</b><br/>
                        Google Ads (AdWords) remarketing service is provided by Google Inc.<br/><br/>
                        You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: <a href="http://www.google.com/settings/ads">http://www.google.com/settings/ads</a><br/><br/>
                        Google also recommends installing the Google <a href="https://tools.google.com/dlpage/gaoptout">Analytics Opt-out Browser Add-on</a> – for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.<br/><br/>
                        For more information on the privacy practices of Google, please visit the <a href="https://policies.google.com/privacy?hl=en">Google Privacy Terms web page</a><br/><br/>
                        <b>Bing Ads Remarketing</b><br/>
                        Bing Ads remarketing service is provided by Microsoft Inc.<br/><br/>
                        You can opt-out of Bing Ads interest-based ads by following their <a href="https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads">instructions</a><br/><br/>
                        You can learn more about the privacy practices and policies of Microsoft by visiting their <a href="https://privacy.microsoft.com/en-us/PrivacyStatement">Privacy Policy page</a><br/><br/>
                        <b>Twitter</b><br/>
                        Twitter remarketing service is provided by Twitter Inc.<br/><br/>
                        You can opt-out from Twitter's interest-based ads by following their <a href="https://support.twitter.com/articles/20170405">instructions</a><br/><br/>
                        "You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page: <a href="https://twitter.com/privacy">https://twitter.com/privacy</a><br/><br/>
                        <b>Facebook</b><br/>
                        Facebook remarketing service is provided by Facebook Inc.<br/><br/>
                        You can learn more about interest-based advertising from Facebook by visiting <a href="https://www.facebook.com/help/164968693837950">this page</a><br/><br/>.
                        To opt-out from Facebook's interest-based ads, follow these <a href="https://www.facebook.com/help/568137493302217">instructions</a> from Facebook<br/><br/>
                        Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance <a href="http://www.aboutads.info/choices/">in the USA</a>, the Digital Advertising Alliance of Canada <a href="http://youradchoices.ca/">in Canada</a> or the European Interactive Digital Advertising Alliance <a href="http://www.youronlinechoices.eu/">in Europe</a>, or opt-out using your mobile device settings.<br/><br/>
                        For more information on the privacy practices of Facebook, please visit <a href="https://www.facebook.com/privacy/explanation">Facebook's Data Policy</a><br/><br/>
                        <b>Pinterest</b><br/>
                        Pinterest remarketing service is provided by Pinterest Inc.<br/><br/>
                        You can opt-out from Pinterest's interest-based ads by enabling the “Do Not Track” functionality of your web browser or by following Pinterest <a href="http://help.pinterest.com/en/articles/personalization-and-data">instructions</a>.<br/><br/>
                        You can learn more about the privacy practices and policies of Pinterest by visiting their <a href="https://about.pinterest.com/en/privacy-policy">Privacy Policy page</a>.
                    </div>
                    
                    <div className="doc-section-title">
                        18. Payments
                    </div>
                    <div className="doc-section-content">
                        We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).<br/><br/>
                        We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.<br/><br/>
                        The payment processors we work with are:<br/><br/>
                        <b>PayPal or Braintree:</b><br/>
                        Their Privacy Policy can be viewed at <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full">Privacy Policy</a><br/><br/>
                        <b>Stripe:</b><br/>
                        Their Privacy Policy can be viewed at: <a href="https://stripe.com/us/privacy">https://stripe.com/us/privacy</a>
                    </div>
                    
                    <div className="doc-section-title">
                        19. Links to Other Sites
                    </div>
                    <div className="doc-section-content">
                        Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.<br/><br/>
                        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                    </div>
                    
                    <div className="doc-section-title">
                        20. Children's Privacy
                    </div>
                    <div className="doc-section-content">
                        Our Services are not intended for use by children under the age of 13 (“<b>Children</b>”).<br/><br/>
                        We do not knowingly collect personally identifiable information from Children under 13. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
                    </div>
                    
                    <div className="doc-section-title">
                        21. Changes to This Privacy Policy
                    </div>
                    <div className="doc-section-content">
                        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.<br/><br/>
                        We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.<br/><br/>
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                    </div>
                    
                    <div className="doc-section-title">
                        22. Contact Us
                    </div>
                    <div className="doc-section-content">
                        If you have any questions about this Privacy Policy, please contact us:<br/><br/>
                        By email: <a href="mailto:support@swingscalp.com">support@swingscalp.com</a><br/><br/>
                        By mail: 2401 Fountain View Drive, Suite 224 #2456, Houston, TX 77057.
                    </div>
                </Box>
            </Box>
        </div>
    )
};

export default PrivacyPolicy;